apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-drupal
  namespace: drupal-argo
  labels:
    app: nfs-drupal
    storage.k8s.io/name: nfs
    storage.k8s.io/part-of: kubernetes-complete-reference
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
