---
- name: MY_SQL. Install packages
  apt:
    name: "{{ apt_database_packages }}"
    state: latest
    update_cache: yes

- mysql_db:
    name: "{{ app_database_name }}"
    encoding: utf8
    login_unix_socket: /var/run/mysqld/mysqld.sock

- mysql_user:
    name: "{{ app_database_user }}"
    password: "{{ app_database_pass }}"
    priv: "{{ app_database_name }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: yes