apiVersion: v1
kind: ConfigMap
metadata:
  name: 12-config-map
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    <title>Pod Information</title>
    </head>
    <body>
    <h1>Pod Information</h1>
    <p>Hostname: HOSTNAME</p>
    </body>
    </html>
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "0%"
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html/
        - name: secret
          mountPath: /root/.ssh/       
      initContainers:
      - name: test
        image: nginx:latest
        command: ["bash", "-c", 'cd /app/; sed -e "s/HOSTNAME/$HOSTNAME/" /app/index.html > /usr/share/nginx/html/index.html'] 
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html
          readOnly: false
        - name: init-index
          mountPath: /app/index.html
          subPath: index.html
          readOnly: false
        - name: ssh
          mountPath: /root/.ssh/
          
      volumes:
      - name: nginx-index
        emptyDir: {}
      - name: init-index
        configMap:
          name: 12-config-map
      - name: ssh
        emptyDir: {}
      - name: secret
        secret:
          secretName: secret-from-manifest
       

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx-service
spec:
        #type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sa
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "nginx-server.k8s-5.sa"
spec:
  rules:
    - host: nginx-server.k8s-5.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80