- hosts: all_workers
  gather_facts: False
  become: true
  vars_files:
    - groupvars.yaml
  tasks:
    - name: Create group
      group:
        name: "{{ item.name }}"
        state: present
      loop: "{{ mygroups }}"

    - name: Create users
      user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        password: "{{ item.password | password_hash('sha512') }}"
        state: present
      loop: "{{ users }}"

    - name: Delete users
      user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        state: absent
      loop: "{{ users }}"

    - name: Delete groups
      group:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ mygroups }}"
