all_workers:
  children:
    work_sa:
      hosts:
        host33:
          ansible_host: 192.168.202.33
        host34:
          ansible_host: 192.168.202.34
        db15:
          ansible_host: 192.168.201.15
  
jump_sa:
  vars:
    env: "it-academy"
  hosts: 
    bastion:
      ansible_host: 178.124.206.53
      ansible_user: jump_sa
      