---
- name: NGINX. Install packages
  yum:
    name: "{{ yum_http_packages }}"
    state: present
  tags:
  - tests

- name: NGINX. Create defaults folders
  file:
    path: "{{ item }}"
    owner: root
    mode: '0755'
    state: directory
  loop:
     - '/etc/nginx/sites-available/'
     - '/etc/nginx/sites-enabled/'
     - '/var/www'

- name: NGINX. Add directory path in nginx.conf
  shell:
    cmd:  sed -i '/^http {/,/^}/!b;/^}/i\     include /etc/nginx/sites-enabled/*.conf;' /etc/nginx/nginx.conf
  run_once: true  

- name: NGINX. Enable and start service
  service:
    name: nginx
    state: started
    enabled: yes
