name: Hello Workflow
on:
  push:
    branches:
      - md-sa2-25-23

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' 
    - name: Check out code
      uses: actions/checkout@v2     
    - name: Run Python script
      run: python hello.py
