apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 1m
    route:
      receiver: 'slack-notifications'
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 20s
      routes:
        - receiver: slack-notifications
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 20s
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - api_url: https://hooks.slack.com/services/TFBPBNB2L/XXXXXXXXXXXXXXXXXXXXX
        channel: '#git_md-sa2-23-23'
        send_resolved: true
        title: |-
            [{{ .Status | toUpper }}] 
        text: |-
            {{ range .Alerts -}}
            *Alert:* {{ .Annotations.title }}
            *Description:* {{ .Annotations.description }}
            *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
      - alert: HostHighCpuLoad
        expr: avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[1m]) * 100) < 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High usage on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has a average CPU idle (current value: {{ $value }}s)"  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        args:
          - "--config.file=/etc/alertmanager/config.yml"
          - "--storage.path=/alertmanager"
        ports:
        - name: alertmanager
          containerPort: 9093
        resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: alertmanager
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
spec:
  selector: 
    app: alertmanager
  type: NodePort  
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-alertmanager
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: alertmanager.k8s-5.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: 8080
