apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
spec:
  containers:
  - name: stress-container
    image: debian
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y stress procps && tail -f /dev/null"]
