---
apiVersion: v1
kind: Secret
metadata:
  name: github-token-secret
type: Opaque
data:
  GITHUB_TOKEN: token
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys-secret
type: Opaque
data:
  SSH_PUBLIC: id_rsa.pub key
  SSH_PRIVATE: id_rsa key
