apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: gitaction
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: sanderknape/github-runner:latest
        env:
        - name: GITHUB_OWNER
          value: EvgeniErmakov
        - name: GITHUB_REPOSITORY
          value: yes-i-still-love-you
        - name: GITHUB_PAT 
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_PERSONAL_TOKEN
