kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 5m
      routes:
        - receiver: slack-alerts
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m

    receivers:
    - name: alert-emailer
      email_configs:
      - to: marchik32@gmail.com
        send_resolved: true
        from: from-email@email.com
        smarthost: smtp.example.com:25
        require_tls: false
    - name: slack-alerts
      slack_configs:
      - api_url: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXX/XXXXXXXXX
        channel: '#monitoring-alerts'
