version: '3'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_SERVER_HOST=mysql
      #- DB_USER=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - DB_SERVER_PORT=3306
      #- DB_PASSWORD=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=UTC
    depends_on:
      - mysql
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - DB_SERVER_PORT=3306
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=UTC
    depends_on:
      - zabbix-server
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysql_data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    environment:
#      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=zabbix
#      - MYSQL_USER=zabbix
#      - MYSQL_PASSWORD=zabbix
#      - MYSQL_DATABASE=zabbix
#      - MYSQL_CHARSET=utf8
#      - MYSQL_COLLATION=utf8_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    restart: unless-stopped
volumes:
  mysql_data:
