apiVersion: v1
kind: Pod
metadata:
  name: self-hosted-runner
spec:
  containers:
  - name: ubuntu
    image: ghcr.io/pluhin/busy-box
    command: ["/bin/sh","-c"]
    args:
      - mkdir actions-runner && cd actions-runner;
        curl -o actions-runner-linux-x64-2.303.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.303.0/actions-runner-linux-x64-2.303.0.tar.gz;
        export RUNNER_ALLOW_RUNASROOT='1';
        tar xzf ./actions-runner-linux-x64-2.303.0.tar.gz;
        ./config.sh --name ubuntu_runner_busy-box --labels linux,runner,busy-box --runnergroup default --url https://github.com/OksanaDemidovec/md-sa2-23-23-github --token XXXXXXXXXXXXXXXXXXXXXXXXXXX;
        ./run.sh;
