---
- name: Check Mount point
  vars:
    mp_used_pers:  "{{ ((item.size_available / item.size_total) | round(4)) * 100}} "
  assert:
    that: mp_used_pers | int >= 60
    success_msg: "OK. Available {{ mp_used_pers }}% of disk space."
    fail_msg: "Oops, not enough disk space. Available {{ mp_used_pers }}%."
  when: item.mount == '/'  
  with_items:
    - "{{ ansible_mounts }}"   

- name: Check RAM
  vars:
    ram_used_pers: "{{ ((ansible_memory_mb.real.free / ansible_memory_mb.real.total) | round(4)) * 100 }}"
  assert:
    that: ram_used_pers | int >= 2
    success_msg: "OK. Available {{ ram_used_pers }}% of RAM."
    fail_msg: "NOT ENOUGH RAM. Available {{ ram_used_pers }}%."

