---

- name: Tasks to create a new user, assign the user to a specific group, and set a password.
  hosts: work_sa

  tasks:
    - name: Create group
      group:
        name: "{{ group_name }}"
        state: present

    - name: Create a Linux User with non-interactive shell
      user:
        name: "{{ user_name }}"
        group: "{{ group_name }}"
        password: "{{ user_password | password_hash('sha512') }}"
        # shell: /sbin/nologin
        state: present
