---
- name: Nginx. Install packages
  yum:
    name: "{{ yum_http_packages }}"
    state: present
  tags:
  - tests

- name: Copy first page
  template:
    src: index.html.j2
    dest: "{{ default_home_centos }}/index.html"
    owner: root
    group: root
    mode: '0755'

- name: Nginx. Enable and start service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Nginx. Enable firewall port
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - "80/tcp"
    - "443/tcp"
  notify:
    - Nginx. reload service firewalld
  tags:
  - tests
