apt_mysql_packages:
  - libmysqlclient-dev
  - imagemagick
  - libmagickwand-dev
  - apache2
  - libapache2-mod-passenger
  - mysql-server
  - mysql-client
  - python3-pymysql
  - python3-mysqldb

app_db_host: "127.0.0.1"
app_db_name: "redmine"
app_db_user: "redmine"
app_db_pass: "redmine"
