---
apiVersion: v1
kind: Namespace
metadata:
  name: self-runner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: self-runner
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
      - name: runner
        image: skalyuga/docker_github_runner:latest
        env:
        - name: RUN_REPO
          value: s-kalyuga/12.k8s-runner
        - name: RUN_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-token
              key: RUN_TOKEN
